#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '🤢 Its raw - Your styling looks wrong.
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤 Get that weak shit out of here! 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed Type check. 
            Type checking gone wrong. Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔 Trying to build now.'

npm run build ||
(
    echo '🔨 Build failed 
            Build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅ Committing now.'